name: clean_architecture_with_getx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.0.7
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1 
  flutter_contacts: ^1.1.7+1
  collection: ^1.17.2
  google_places_flutter: ^2.0.6
  geocode: ^1.0.3
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  device_preview: ^1.1.0
  record: ^5.0.1
  audioplayers: ^5.2.0
  firebase_messaging: ^14.7.4
  firebase_core: ^2.22.0
  auto_size_text_field: ^2.2.2
  flutter_google_places_sdk: ^0.3.7
  geolocator: ^10.1.0
  flutter_local_notifications: ^16.2.0
  image_cropper: ^5.0.1
  universal_html: ^2.2.4
  flutter_libphonenumber: ^2.2.1
  country_list_pick: ^1.0.1+6
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  device_info_plus: ^9.1.1
  url_launcher: ^6.2.4
  http_parser: ^4.0.2
  http: ^1.2.0
  file_saver: ^0.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Cherolina
      fonts:
        - asset: assets/fonts/Cherolina.ttf
          weight: 500
